/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyGradleProject;
import java.util.Scanner;
public class Library {
    public static void main(String args[]) {
    	
    	Scanner sc = new Scanner(System.in);
    	
    	System.out.println("Enter first number:");
    	int a = sc.nextInt();
    	System.out.println("Enter second number:");
    	int b = sc.nextInt();
    	
    	System.out.println("Sum of the numbers is: "+(a+b));
    	
    }
}
